### ISSUE TITLE
Mastery Page - Rune Page - Summs

### ISSUE THREAD

**Issue by xM4st3r** [Darker/auto-client#17]
Hi , 

the tool work but i think it's too fast because : 

- after pick the champion , he pick the summs but don't go out for pick the second summs
- after the pick of summs , the tool go to mastery pages but didn't select anything
- don't pick rune page because stuck in mastery select page.

**Comment by Darker** [comment]
Hello,
thanks for reporting this. Please note that it's little different on every PC, so what you reported doesn't happen to me. I'll need your help to fix it.

The tool shouldn't puck sums if already selected. That's a nw feature - maybe there was an error and the tool thought it's selected but it wasn't.

I will improve the mastery algorithm. Currently it doesn't check whether the popup appeared - that will be fixed.

Btw does it happen every time to you, or just sometimes?

**Comment by xM4st3r** [comment]
Hmm like you said , i chose sums but it was different : pick smite and shield before using tool and configure it to choose ignite and flash after opening.
I think it happen every time but not sure because my PC is hot sometime.

**Comment by Darker** [comment]
I selected Smite and Barrier in the game lobby. I configured the tool to select Ignite and Flash. It worked:

![image description](http://i.stack.imgur.com/tNGvI.png)

Did I understand correctly what you meant?

**Comment by xM4st3r** [comment]
Yeah , maybe my pc is just a little bit slow hmm

**Comment by Darker** [comment]
It should work on any PC though. I'll try to improve this and then let you know when there's a new version to test.

**Comment by Darker** [comment]
@xM4st3r Hi, I made a beta release which should fix getting stuck on mastery select. It should now wait for the window to appear. See here: https://github.com/Darker/auto-client/releases/tag/v4.2-beta

This probably doesn't fix all problems you reported, but I need to know whether I am taking the right approach to fix this. Let me know.

It would be best if you could give me a video or a console output of the program (or best, both). I understand that making a video is some work but currently I'm just guessing.

**Comment by xM4st3r** [comment]
I'll go see that

**Comment by xM4st3r** [comment]
Well @Darker the autoclient didn't do anything , only accept the queue.

**Comment by Darker** [comment]
Hi.
Apparently AutoClient is not very reliable for you. But without some meaningful info about what's wrong, I can't really fix this. I've been playing a lot this weekend and the client has not failed me a single time.

Use `run_with_commandline.bat` to see output of the program, maybe there will be hint of what's wrong.

**Comment by xM4st3r** [comment]
Okay maybe it was only yesterday that didn't work because i had this today : 
!(https://cloud.githubusercontent.com/assets/12584218/15286141/7cb51bd6-1b5b-11e6-829c-0e729161621f.png)

**Comment by Darker** [comment]
The first screenshot:The lobby gone message appears when the program no longer sees game lobby (eg. chat input and few other points). I can see it failed to pick masteries and first summoner spell. There were more improvements in the 4.2 release, make sure you have it, but still, this didn't happen even before. The masteries work perfectly for me. When you click the button to edit masteries, does it take more than 5 seconds to appear?

The second thing is a bug that I really should fix. Basically, when accepting the program just looks for white point at certain place - but sometimes there's a white point even though there's not the accept dialog. Adding more points to check (eg. blue) will fix that. It also happens when you minimize the window (then all points are white for some reason). Will be fixed in next release.

Could you try one thing? Click `Tools -> Debug -> Create remote window` in the program. That will make another big window that exactly shows how my program sees the LoL PVP.net Client. It also allows you to click on things and those click can propagate to the Client. Try clicking near button corners and such to see if the clicking is precise - it must be absolutely precise. If it's not, there is some problem with targeting points on your screen.

**Comment by xM4st3r** [comment]
I got that when going to remote window 
![sans titre](https://cloud.githubusercontent.com/assets/12584218/15328002/b9928aa4-1c53-11e6-9133-f8c1e24197d4.png)

For the masteries , it take less than 5 seconds

**Comment by Darker** [comment]
Hmm, one issue here is that you have not windows Aero function enabled. This means my program cannot see PVP.net client when another window is over it - instead it sees the other window. What your're seeing is the result of the visible part to the right being copied over and over as my program is now taking screenshots of itself. So one thing you must make sure of is that the PVP.net is always on top - or that you enable windows Aero.

Unfortunately my program is not able to know whether Aero is on or off so it couldn't warn you. Also, Aero is not available on new versions of windows.

**Comment by xM4st3r** [comment]
Okay thanks
